name: BBBBBTest

on: [push, pull_request]

env:
  cache-version: v1

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Cache dependencies
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ env.cache-version }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-${{ env.cache-version }}-
      - name: Install dependencies
        run: npm ci
      - name: Run lint
        run: npm run lint
      - name: Run type tests
        run: npm run typecheck
      - name: AWS-cli Check.
        run: aws --version
